language: node_js
node_js:
  - "7.10.1"
  - "8.14.1"
  - "9.11.2"
  - "10.14.2"
  - "11.5.0"
script: "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
