language: node_js
node_js:
  - "8"
  - "10"
  - "12"
services:
  - mongodb
script:
  - "npm run test"
  - "npm run-script test-coverage"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
